name: Update Geo Files

on:
  schedule:
    - cron: "0 */3 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Download geo files
        run: |
          mkdir files

          curl -fL \
            https://connect.vpnhub.shop/geo/geoip.dat \
            -o files/geoip.dat

          curl -fL \
            https://connect.vpnhub.shop/geo/geosite.dat \
            -o files/geosite.dat


      - name: Update release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Geo Files
          body: |
            Automatically updated geo files.
          files: |
            files/geoip.dat
            files/geosite.dat
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}