name: Update Happ Subscription

on:
  schedule:
    - cron: "30 */3 * * *"

  workflow_dispatch:


permissions:
  contents: write


jobs:
  update:
    runs-on: ubuntu-latest

    timeout-minutes: 10


    steps:

      - name: Download subscription
        run: |
          curl \
            --fail \
            --location \
            --max-time 120 \
            "${{ secrets.VPN_SUB_URL }}" \
            -o subscription.base64


      - name: Decode subscription
        run: |
          base64 -d subscription.base64 > happ-subscription


      - name: Validate
        run: |
          echo "Result:"
          head -c 100 happ-subscription
          echo

          if [ ! -s happ-subscription ]; then
            echo "Empty subscription"
            exit 1
          fi


      - name: Update release
        uses: softprops/action-gh-release@v2

        with:
          tag_name: latest
          name: Latest Happ Subscription

          files: |
            happ-subscription

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}