name: Update Happ Subscription

on:
  schedule:
    # каждые 3 часа
    - cron: "30 */3 * * *"

  workflow_dispatch:


permissions:
  contents: write
  pages: write
  id-token: write


jobs:

  build:

    runs-on: ubuntu-latest


    steps:

      - name: Download subscription
        run: |
          curl \
            --fail \
            --location \
            --max-time 120 \
            "${{ secrets.VPN_SUB_URL }}" \
            -o subscription.base64


      - name: Decode subscription
        run: |
          base64 -d subscription.base64 > subscription.txt


      - name: Validate subscription
        run: |
          echo "Subscription preview:"
          head -c 200 subscription.txt
          echo

          if ! grep -q "://" subscription.txt; then
            echo "Invalid subscription format"
            exit 1
          fi


      - name: Prepare Pages
        run: |
          mkdir public
          cp subscription.txt public/happ-subscription


      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public



  deploy:

    needs: build

    runs-on: ubuntu-latest


    environment:
      name: github-pages


    permissions:
      pages: write
      id-token: write


    steps:

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4